- name: Sabre Ansible Playbooks
  hosts: all
  user: predator
  sudo: no
  gather_facts: False
  tasks:
   - include: tasks/install.yaml
     when: "{{appdynamics['install']}} == true"
   - debug: msg="reading from {{env_name}}"
