---
- name: ElasticSearch Playbook
  hosts: localhost
  vars:
    tmpdir: /tmp/apps/elasticsearch
    appname: ElasticSearch Installation and Configuration
    srcversion: elasticsearch-1.7.3.tar.gz
    latversion: elasticsearch-1.7.3
    srcurl: https://download.elastic.co/elasticsearch/elasticsearch
  tasks:
    - include: tasks/install.yaml
